### ISSUE TITLE
Error when editing .sass files

### ISSUE THREAD

**Issue by LandonSchropp** [atom/autocomplete-css#35] opened 2015-09-15 20:29 UTC
I keep seeing this error when editing `.sass` files:

```
TypeError: Cannot read property 'concat' of null
  at Object.module.exports.getSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35:65)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

This seems to happen when I make a small syntax error in the file, such as inserting a semicolon. However, I haven't been able to come up with reliable repro steps.
- Atom 1.0.11
- autocomplete-css 0.10.1
- OS X 10.10.2

**Comment by winstliu** [comment] 2015-09-15 22:54
Duplicate of #27, please subscribe there for updates.

**Closed as completed by winstliu** 2015-09-15 22:54 UTC
