### ISSUE TITLE
Autocomplete attempts to add CSS property after commas

### ISSUE THREAD

**Issue by benogle** [atom/autocomplete-css#21] opened 2015-07-08 20:17 UTC
_From @geebru on July 8, 2015 18:53_

See small screencast - http://cl.ly/3V1R3d0r1F3v

Mac OSX 10.10.4 - Atom 1.0.1 - No errors / crashes.

I've noticed when attempting to chain CSS selectors (in SCSS) the autocomplete pop-up will appear after I've typed the comma, meaning when I try to hit Return to go to the next line, I get width: width; instead of a new line.

I changed my settings from autocomplete on Tab to autocomplete on Enter after installing Emmet so it's well within my capabilities to circumvent the issue currently but curious as to why it pulls up this prompt when typing commas in CSS (SCSS)?

_Copied from original issue: atom/atom#7799_

**Comment by geebru** [comment] 2015-07-08 20:26
Looks like this may be a duplicate of #18 - only difference being I see it as a bug as I'm not sure why it would try autocompleting after a comma vs. increasing pop-up delay time.

Thanks for moving this @benogle!

**Closed as completed** 2015-07-21 01:08 UTC
Labels: bug
