### ISSUE TITLE
Invalid values showing (and first) for CSS property values

### ISSUE THREAD

**Issue by codeopensrc** [atom/autocomplete-css#17] opened 2015-06-18 19:14 UTC
Not sure if others are experiencing this as well (although a slight variation is mentioned here #15).

Also I apologize if this is a "feature" and not an issue and if so, please close it.

Since the new autocomplete-plus changes, I've been having invalid property values showing first, tabbing, and getting an incorrect one. It has almost (almost, not entirely) defeated the point of using autocomplete css.

Ex.

div {  
    text-align: ce  
    postition: re  
}

The first choice for text-align for the majority of people is center, not charset (invalid value). Same as position, most people are looking for relative, not review (again, an invalid value, which adds something like  // REVIEW:  )

I'd like to be able to see it only show valid values for the css property, but it appears to be just doing a lookup for all css props/values that contain those letters (not even in consecutive order). I've attempted to enable the strict matching in the autocomplete-plus package to match my prefix exactly, but it doesn't appear to be working (Maybe I'm doing it wrong?).

I'll attempt (albeit I know unsuccessfully) to find a fix, but if anyone has encountered this or has suggestions/quick fix, please let me know.

Thanks

**Comment by benogle** [comment] 2015-06-18 19:42
Can you take a screenshot? Do you have emmet installed? Can you try starting atom via safe mode: `atom --safe .` Is the error still there?

**Comment by codeopensrc** [comment] 2015-06-18 20:49
I wouldn't call it an error, just an inconvenience really. I was curious if others were experiencing this and had a solution/how they handled it and whether it was intended or not.

Its interesting because right after the colon it shows only the valid values, but once you start entering text it switches. I don't have emmet installed either. Also does it when launched using `atom --safe` (last screenshot)

![css ex 3](https://cloud.githubusercontent.com/assets/9301207/8241679/a1eee32a-15bf-11e5-8110-6bc848e2a9c7.png)

![css ex 1](https://cloud.githubusercontent.com/assets/9301207/8241515/93f220b2-15be-11e5-906c-f3de8562b135.png)
![css ex 2](https://cloud.githubusercontent.com/assets/9301207/8241516/95f17098-15be-11e5-9196-7b0e692d6361.png)

![css ex 4](https://cloud.githubusercontent.com/assets/9301207/8241899/d11c7ada-15c0-11e5-9548-73a856f83b02.png)

It's just a little irritating because before you could enter 1 or 2 letters, tab, done. Now 3 seems to be the magic number (havn't tested).

**Comment by winstliu** [comment] 2015-06-18 21:04
This seems like a duplicate of atom/autocomplete-plus#465.

**Comment by benogle** [comment] 2015-06-18 21:43
Sorry, I didnt understand the original issue. These snippets shouldnt be showing up. When you expand the `review` snippet, what happens?

I wonder where these snippets are coming from. Do you have these snippets defined in your snippets.cson?

> Now 3 seems to be the magic number (havn't tested).

Yeah, 3 is the minimum prefix length for showing completions for most providers.

**Comment by codeopensrc** [comment] 2015-06-18 21:56
Here are the results from tabbing on the snippets. These are just examples and I'm not sure all the cases where this happens, it's just the ones I remembered and quickly duplicated. I haven't really messed with configurations beyond a few keybinding. My snippets.cson is empty in the last screenshot. The only packages I have are React, autocomplete-plus, minimap, and maybe like one or two more (beyond the built-in packages).

Edit: I found a package called snippets (assuming built-in) and when disabled, the snippet then just completes with the word itself instead of the snippet, but is still present as the first choice. I'll keep checking.

![css ex1](https://cloud.githubusercontent.com/assets/9301207/8243122/3b0a49c4-15c9-11e5-994b-cfd485271366.png)
![css ex2](https://cloud.githubusercontent.com/assets/9301207/8243123/3c4872d4-15c9-11e5-93b5-6308a3903c4d.png)

![snippets](https://cloud.githubusercontent.com/assets/9301207/8243211/cd5193c8-15c9-11e5-9622-808321b9da0d.png)

**Comment by codeopensrc** [comment] 2015-06-18 22:09
Disabled autocomplete-snippets and its removes the snippets, but other choices still remain. Autocomplete-html has also been disabled throughout all the screenshots. Only autocomplete packages active are -css and -plus.

Hopefully these screenshots help. Thanks for checking it out as well.

![css ex1](https://cloud.githubusercontent.com/assets/9301207/8243415/b9083816-15cb-11e5-8177-0b4874b962af.png)
![css ex2](https://cloud.githubusercontent.com/assets/9301207/8243417/bb018b22-15cb-11e5-82cf-b2df2aea57bf.png)

**Comment by benogle** [comment] 2015-06-18 22:58
What language are you in? css? less? scss?

**Comment by codeopensrc** [comment] 2015-06-19 00:31
All of the screenshots but the screenshot with blah.css up at the top are in less. I wanted to check to see if it was a less only issue and found it happened with .css as well.

Are you not getting the same thing with yours? If not, then it must be either the React package or something else.

**Comment by benogle** [comment] 2015-06-19 01:12
Super sorry about this. I'll dig into it in the next couple of days.

**Comment by benogle** [comment] 2015-06-19 15:13
This is a couple of issues.
- [x] css snippets are using too liberal a scope
- [x] todo snippets are using too liberal a scope https://github.com/atom/language-todo/commit/6a90db502e15b91f5b295129b285b87f73f6b0ac
- [x] scope issues in autocomplete css

I'm traveling today, but I should get to totally fixed up monday.

**Closed as completed** 2015-06-22 02:54 UTC
Labels: more-information-needed

**Comment by benogle** [comment] 2015-06-22 02:56
Thanks for reporting this. The combination of little errors really added up here.
