### ISSUE TITLE
The autocomplete plugins doesn't work

### ISSUE THREAD

**Issue by Tricker39** [atom/autocomplete-css#46] opened 2016-04-06 02:02 UTC
When I write css code inline, but the autocomplete-css does't work. It is not help me to complete the code.I think many people meet this question,

Best wishes!
Mascot

**Comment by winstliu** [comment] 2016-04-06 12:13
HI @Mascot1, thanks for reporting!  This looks like a duplicate of #31 though, so feel free to subscribe there for updates.

**Closed as completed by winstliu** 2016-04-06 12:13 UTC
Labels: duplicate
