### ISSUE TITLE
Add PostCSS support

### ISSUE THREAD

**Issue by ai** [atom/autocomplete-css#91] opened 2017-04-23 12:38 UTC
### Description

Add PostCSS file types for CSS autocomplete.

### Steps to Reproduce

1. Open CSS file — autocomplete works.
2. Install [language-postcss](https://atom.io/packages/language-postcss).
3. Change syntax to PostCSS or open `.pcss`/`.sss` file.

**Expected behavior:** Autocomplete should works.

**Actual behavior:** Autocomplete doesn’t work.

**Reproduces how often:** Always.

### Versions

```
➤ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
➤ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.9.3
```

### Additional Information

@50Wliu I am not sure, that it is only `autocomplete-css` issue. Maybe we need to chnge other plugins.

But this feature is very important for PostCSS ecosystem. If we need to change other plugins — just say plugins name and I will speak with plugin authors.

**Comment by winstliu** [comment] 2017-04-23 15:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #37. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed as completed by winstliu** 2017-04-23 15:28 UTC
Labels: duplicate
