### ISSUE TITLE
Setting to disable automatic colon insertion?

### ISSUE THREAD

**Issue by arxpoetica** [atom/autocomplete-css#63] opened 2016-08-25 23:44 UTC
Is this possible? Stylus, for example, makes colons optional, and I prefer to _not_ use them.

**Comment by winstliu** [comment] 2016-08-27 17:20
This is a duplicate of #2 - feel free to subscribe there for updates.

**Closed as completed by winstliu** 2016-08-27 17:20 UTC
Labels: duplicate

**Comment by arxpoetica** [comment] 2017-08-12 18:49
I'm revisiting this a year later for the reason that it was marked as a duplicate of #2 (I can see your point, but...)...but the `+1`s in issue #2 are ignored, and there are plenty of them.

Any reason we can't reopen this to track the issue of ignoring colons specifically?

Alternately, can issue #2 actually handle that issue?

Thanks.

**Comment by winstliu** [comment] 2017-08-12 22:12
The +1s aren't being ignored; it's just that the Atom team has higher-priority work to do and @mehcode hasn't been able to finish the PR yet.  We like to keep our open issues list as compact as possible as it's representative of our backlog.

#2 talks a lot about disabling automatic colon insertion.  In the event that #2 is closed and there is no way to disable automatic colon insertion when using Stylus, then just ping me again and I will gladly reopen this issue.

**Comment by mehcode** [comment] 2017-08-13 00:17
It's really as simple as I no longer use stylus and have trouble getting time (and motivation) to work on a thing that I don't use.

If anyone wants to pick it up I don't mind helping with direction of how it can be done.
