### ISSUE TITLE
The value can't see

### ISSUE THREAD

**Issue by Tricker39** [atom/autocomplete-css#42] opened 2016-03-23 07:05 UTC
And I write property name and when I write the values, but it doesn't work

**Comment by winstliu** [comment] 2016-03-28 14:37
@Mascot1 Please see [How do I submit a (good) bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report).

In the meantime this looks like a tentative duplicate of #31.

**Closed as completed by winstliu** 2016-03-28 14:37 UTC
Labels: duplicate
