### ISSUE TITLE
Doesn't show some completions when properties inlined

### ISSUE THREAD

**Issue by LantosIstvan** [atom/autocomplete-css#31] opened 2015-08-06 10:29 UTC
When I write "dis", the possible commands will be offered, I choose "display". But next, there's no any sub-options offered, even if I start to type "block". This is a huge miss from Adobe Dreamweaver. Can we see it in autocomplete-css?

**Comment by benogle** [comment] 2015-08-06 17:47
This works for me. 

![screen shot 2015-08-06 at 10 46 16 am](https://cloud.githubusercontent.com/assets/69169/9118900/65a0d6be-3c28-11e5-871b-faa16554f927.png)

What kind of file are you in? What version of atom? Is autocomplete-css enabled? Please quit atom completely and run `atom --safe .`. Is the issue still there?

**Comment by LantosIstvan** [comment] 2015-08-06 19:41
I re-structured my CSS file from one-liners to opened tags. Seems like when you write your code in one line by tag, only showing an irrelevant list, sometimes no list at all:

![autocomplete-css-one-liner-bug](https://cloud.githubusercontent.com/assets/5021728/9121625/c7f47af4-3c83-11e5-908c-60e0f63c99f7.png)

Atom 1.0.4
autocomplete-css enabled

**Comment by benogle** [comment] 2015-08-06 20:02
Ok, i've changed the title.

**Comment by ck-jrd** [comment] 2015-08-07 13:36
This looks like a dupe of my #20, which still doesn't look like it's been fixed.

**Comment by indrimuska** [comment] 2015-09-28 10:29
Same problem here.
This is very problematic to me, since all my styles are inlined.

**Comment by panosdotk** [comment] 2016-01-15 14:12
I have the same problem

**Comment by vadimsgr** [comment] 2016-01-19 13:38
Same here. Any ETA?

**Comment by zalog** [comment] 2016-01-24 10:33
Same here :)

**Comment by 758915145** [comment] 2016-03-22 09:30
那么这个bug会被修复吗？

**Comment by winstliu** [comment] 2016-03-28 14:34
> 那么这个bug会被修复吗？

Translation: "Then will this bug be fixed?"

To my knowledge, no one is working on this right now, but help is definitely welcome (as indicated by the `help-wanted` label).

**Comment by winstliu** [comment] 2016-09-29 16:02
I've been investigating this bug.  The problem stems from the `propertyNameWithColonPattern` regex which is used to determine which property name autocomplete-css should be completing values for.  The regex is `/^\s*(\S+)\s*:/`, which clearly doesn't work well for inlined values.  Looking into alternative regex patterns...

**Comment by winstliu** [comment] 2016-09-29 16:30
![css-inline-values-autocompletion](https://cloud.githubusercontent.com/assets/2766036/18962824/52404b0a-8640-11e6-8af1-c5fe5d41b85c.gif)
:wink:

There's still one bug that I have to work out, where you can't actually start typing the value (if you do, it goes back to the old property-name-only behavior).

EDIT: ^ Fixed!  Expect a PR soon - just need to work out some specs for this.

**Closed as completed** 2016-09-30 00:39 UTC
Labels: bug, help-wanted
